services:
  web:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
    stdin_open: true
    tty: true 